# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/ZJUI/ECE385/labs/final/final_project/final_project.srcs/sources_1/bd/mb_lab7/ip/mb_lab7_axi_gpio_0_1/mb_lab7_axi_gpio_0_1.xci
# IP: The module: 'mb_lab7_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZJUI/ECE385/labs/final/final_project/final_project.gen/sources_1/bd/mb_lab7/ip/mb_lab7_axi_gpio_0_1/mb_lab7_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_lab7_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/ZJUI/ECE385/labs/final/final_project/final_project.gen/sources_1/bd/mb_lab7/ip/mb_lab7_axi_gpio_0_1/mb_lab7_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_lab7_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/ZJUI/ECE385/labs/final/final_project/final_project.gen/sources_1/bd/mb_lab7/ip/mb_lab7_axi_gpio_0_1/mb_lab7_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_lab7_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/ZJUI/ECE385/labs/final/final_project/final_project.srcs/sources_1/bd/mb_lab7/ip/mb_lab7_axi_gpio_0_1/mb_lab7_axi_gpio_0_1.xci
# IP: The module: 'mb_lab7_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ZJUI/ECE385/labs/final/final_project/final_project.gen/sources_1/bd/mb_lab7/ip/mb_lab7_axi_gpio_0_1/mb_lab7_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_lab7_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/ZJUI/ECE385/labs/final/final_project/final_project.gen/sources_1/bd/mb_lab7/ip/mb_lab7_axi_gpio_0_1/mb_lab7_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_lab7_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/ZJUI/ECE385/labs/final/final_project/final_project.gen/sources_1/bd/mb_lab7/ip/mb_lab7_axi_gpio_0_1/mb_lab7_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_lab7_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
